config/routes.rb
FisioApp::Application.routes.draw do
  
  resources :supports, :only => [:new, :create]
  
	match '/servicios', :to => 'pages#servicios' 
	match '/aplicacionesweb',	:to => 'pages#aplicacionesweb' 
	match '/servicios', :to => 'pages#servicios' 
  match '/serviciosweb', :to => 'pages#serviciosweb' 
  match '/paquetesweb', :to => 'pages#paquetesweb' 
  match '/appsmartphones', :to => 'pages#appsmartphones'
	root :to => 'pages#inicio'
  

end

app/models/support.rb
class Support 
  include ActiveModel::Validations
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates_presence_of :email, :sender_name, :support_type, :content 
    # to deal with form, you must have an id attribute
    attr_accessor :id, :email, :sender_name, :support_type, :content
    validates :email, :format  => { :with => email_regex }
  
    def initialize(attributes = {})
      attributes.each do |key, value|
        self.send("#{key}=", value)
      end
      @attributes = attributes
    end
  
    def read_attribute_for_validation(key)
      @attributes[key]
    end
  
    def to_key; end
  
    def save
      if self.valid?
        Notifier.support_notification(self).deliver
        return true
      end
      return false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def inicio
  	@title = "Inicio"
  end
  def contacto
    @title = "Contacto"
  end
  def servicios
  	@title = "Servicios"
  end
  def paquetesweb
    @title = "Paquetes Web"
  end
  def serviciosweb
    @title = "Servicios Web"
  end
    def aplicacionesweb
  	@title = "aplicacionesweb"
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  def new
    @support = Support.new(:id => 1)
  end
  
  def create
    @support = Support.new(params[:support])
    if @support.save
      flash.now[:success] = "Se ha enviado correctamente el formulario"
      render 'new'
    else
      flash.now[:error] = "Error al enviar el mensaje"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo
		image_tag("logo.png", :alt => "Usabi - Logo")
	end
	
	def promocion
	  image_tag("promocion.png", :alt => "Web Mini 50 €", :class => "promocionimg" )
	end
	
	def title
	end
	def plantilla1
	  image_tag("plantilla1.png", :alt => "Web Básica: desde 170€", :class => "ejemploimg")
	end
	def plantilla2
    image_tag("plantilla2.png", :alt => "Web Estándar: desde 300€", :class => "ejemploimg")
  end
  def plantilla3
    image_tag("plantilla3.png", :alt => "Web Empresa: desde 700€", :class => "ejemploimg")
  end
  def plantilla4
    image_tag("plantilla4.png", :alt => "Tienda online: desde 600€", :class => "ejemploimg")
  end
  def plantilla5
    image_tag("plantilla5.png", :alt => "Web Personalizada", :class => "ejemploimg")
  end	
	def modulos
	  image_tag("appmodulares.png", :alt => "Aplicaciones modulares")
	end
	def seo
	  image_tag("seo.png", :alt => "Posicionamiento en Internet")
	end
	 def iphone
    image_tag("iphone-sdk.png", :alt => "Desarrollo para Android/iOs")
  end
  def facebook
    image_tag("icono-facebook.png", :alt => "Facebook de Usabi")
  end
  def twitter 
    image_tag("icono-twitter.png", :alt => "Síguenos en Twitter")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/layouts/_footer.html.erb
<footer class="round"> 
<div>
		Nos encontramos en: C/ Cayetana Manrique, 19, Las Palmas de Gran Canaria<br>
		mobile: +34 629 47 77 78<br>
		phone: +34 928 22 63 59<br>
		mail: info@usabi.es<br>
</div>
<div>

<%= link_to twitter, "http://twitter.com/_usabi"%>
<%= link_to facebook, "http://www.facebook.com/pages/Usabi/212986768742036?sk=wall"%>

</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<%= link_to logo, root_path %>
		<ul class="borderderecho"> <%= link_to "Inicio", root_path %></ul>
		<ul class="borderderecho"><%= link_to "Servicios", servicios_path %>
			<li><%= link_to "Aplicaciones Web", aplicacionesweb_path %></li> 
			<li><%= link_to "Apps para smartphones", appsmartphones_path %></li>
			<li><%= link_to "Paquetes web", paquetesweb_path %></li>
			<li><%= link_to "Servicios web", serviciosweb_path %></li>

		</ul>
		<ul > <%= link_to "Contacto", new_support_path %></ul>
	</nav></header>

app/views/layouts/_promotion.html.erb
<div class="promocion">
	<%= link_to promocion, paquetesweb_path %>
	<h1>
		Promoción Verano!!<br>
		Su página web desde 50€ *
	</h1>
	<h2>
		No se complique la vida, si su negocio necesita <br>
		tener visibilidad en Internet, esta  <br>
		es la solución. <br>
	</h2>
	<h6>* No se incluye el dominio ni hosting. Coste aprox. 4,99/mes </h6>

</div>



app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]--> 
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %> 
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]--> 
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html><html> 
	<head>		<title><%= @title %></title>		<%= csrf_meta_tag %> 
		<!--since the HTML5 standard is new, some browsers (especially Internet Explorer) don’t yet fully support it, so we include some JavaScript code (known as an “HTML5 shiv”) to work around the issue-->
		<!--[if lt IE 9]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
		<!--
		<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
		<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
		-->
		<%= render 'layouts/stylesheets' %>
		<!--Este código es para considerar versiones inferiores al IE8 -->
		<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]--> 		<%= stylesheet_link_tag 'custom', :media => 'screen' %>
		
		</head>	<body> 
		<div class="container">
		<%= render 'layouts/header' %>
		<section class ="round">				<% flash.each do |key, value| %> <div class="flash <%= key %>">				<%= value %></div>			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		</div>	</body> 
</html>

app/views/notifier/support_notification.html.erb
<h5>Nombre del que lo envía:</h5>  <%= @sender.sender_name%><br />
<h5>Contenido: </h5><%= @sender.content%><br />
<h5>Email:</h5> <%= @sender.email%><br />

app/views/pages/aplicacionesweb.html.erb
<%= render 'layouts/promotion' %>

<h1>
	Aplicaciones web
</h1> 
<p>La tecnología web nos permite crear aplicaciones que sean utilizadas 
desde navegadores, bien accesibles desde redes locales o accesibles desde Internet. 
A esto se le denomina Cloud Computing.

Disponemos de  distintos módulos que permitirán la gestión de una empresa y dependiendo
de las necesidades de su empresa se contratará un paquete de módulos u otro.

Por ejemplo, teniendo los siguientes módulos:
	<%= link_to modulos %> 
<b>
<dl>
	<dd>Módulo para el registro de clientes</dd>
	<dd>Módulo de pagos</dd>
	<dd>Módulo de informes</dd>
	<dd>Módulo de reservas</dd>
	<dd>...</dd>

</dl>
</b>
Si usted tiene un gimnasio, podría necesitar el módulo de pago de coutas y el módulo de registro
de clientes. Sólo pagaría por esos módulos!. Si por el contrario es dentista y necesita además
el módulo de reservas, pues se añadiría al paquete.

Cada módulo tiene un coste mensual:<br><br>
<b><dl>
	<dd>Módulo sencillo: 4,99 € /Mensual</dd>
	<dd>Módulo estándar: 6,99 € /Mensual</dd>
	<d>Módulo complejo: 9,99 € /Mensual</dd>
</dl></b>

¿Por qué el pago es mensual? porque <b>SÓLO</b> debe pagar el software mientras lo use y además siempre estará
actualizado a la última versión desarrollada.

Si los módulos "prefabricados" no se adaptan a sus necesidades, siempre se puede desarrollar la aplicación a su medida.
</p>

app/views/pages/appsmartphones.html.erb
<%= render 'layouts/promotion' %>

<h1>
	Desarrollo para Ipad, Iphone y smartphones con Android
</h1> 
<p>

Mediante las aplicaciones móviles, usted puede dar servicios a sus clientes o 
bien gestionar su empresa desde su teléfono. Si necesita una aplicación para el 
Iphone o Ipad, o cualquier dispositivo con Android, la solución se la ofrecemos 
desde Usabi. 

Te garantizamos desarrollar tus aplicaciones en el menor tiempo y 	<%= link_to "presupuesto", new_support_path %> .


Otro servicio asociado a los dispositivos móviles es la adaptación de tu página web para su visualización desde 
este tipo de terminales. 

Nuestro objetivo es ofrecerle un servicios integral de calidad y creatividad, diseñar y desarrollar su aplicación. <br>
	<%= link_to iphone %> 
</p>

app/views/pages/inicio.html.erb
<%= render 'layouts/promotion' %>
<h1>
Usabi, tu socio tecnológico
</h1> 
<p>
<h5>Usabi es una empresa de Desarrollo de Software a medida basado 
en metodologías de desarrollo ágil y que cuenta con un equipo 
altamente cualificado.
</h5>
<div class="columna3" style="float: right">
	<h4>¿Cuales son las fases en el desarrollo del proyecto?</h4>
		<ol >
			<li>Realizamos el análisis de sus necesidades</li>
			<li>Le presentamos una propuesta de solución tecnológica</li>
			<li>Diseñamos y desarrollamos el proyecto, conjuntamente con usted</li>
			<li>Finalmente implantamos dicha solución en su empresa</li>
			<li>Ofrecemos formación y soporte sobre la misma</li>
			<li>Realizamos el análisis de sus necesidades.</li>
		</ol>
		Nuestra solución es integral, usted sólo debe preocuparse de validar que el proyecto sigue
		las directrices de sus necesidades.
</div> 
<div class="columna3" style="float: left">
		<h4>Principalmente, ¿qué hacemos?</h4>
			Nuestros servicos están orientados a:
			<ul>
				<li>Desarrollo sitios web. Desde webs básicas hasta tiendas virtuales, módulos de 
				gestión de empresa online o CRM entre otros ejemplos.</li>
				<li>Desarrollo de software para smartphones (Iphone y Android).</li>
			</ul>
</div>
<div class="columna3" style="margin-left: 34%">
	<h4>¿Cuál es nuestro principal objetivo?</h4>
		Nuestro principal objetivo es que el software desarrollado se <b> adapte a las 
		necesidades del cliente </b> y no lo contrario. Por ello, dentro de nuestro modelo 
		de fabricación de software, mantenemos reuniones periódicas con nuestros 
		clientes para revisar la evolución del proyecto y marcar los siguientes 
		objetivos a desarrollar. Lo que deseamos, es ser sus socios tecnológicos y que nuestra
		relación no sea simplemente comercial.
</div>

app/views/pages/paquetesweb.html.erb
<%= render 'layouts/promotion' %>

<h1>
	Su negocio en Internet
</h1> 
<p>
La solución para que su negocio tenga presencia en Internet. 

Podrás elegir entre las siguientes soluciones. Si tus necesidades no entran en ninguna de las soluciones propuestas, o está a medio camino entre una
y otra, no dudes en ponerte en 	<%= link_to "contacto", new_support_path %>
 con nosotros para encontrar el mejor presupuesto.
<br />
<div class="columna2" style="float: left">
	<h3>Web Mini: desde 50€ </h3>
	Promoción de verano!, por sólo 50€ tenga presencia en Internet. <br>
	Creación de una página principal + un formulario de contacto.<br><br><br>
	<%= link_to promocion %> 
</div>

<div class="columna2" style="float: right">
	<h3>Web Básica: desde 170€</h3>
	Creación de un apágina principal + 3 apartados de contenido + formulario de contacto <br>
	<%= link_to plantilla1 %>
</div>
<div class="columna2" style="float: left">
	<h3>Web Estándar: desde 300€</h3>
	Creación de un apágina principal + 10 apartados de contenido + formulario de contacto <br>

	<%= link_to plantilla2 %>
</div>
<div class="columna2" style="float: right">
	<h3>Web Empresa: desde 700€</h3>
	Creación de un apágina principal + 
	15 apartados de contenido + formulario de contacto + Boletín de noticias
	+ Enlaces a redes sociales Facebook y Twitter + Optimización para el posicionamiento web
	+ Disponibilidad de dos idiomas (no incluye la traducción) <br>

	<%= link_to plantilla3 %>
</div>
<div class="columna2" style="float: left">
	<h3>Tienda online: desde 600€</h3>
	Funcionalidad para gestionar un catálogo de productos y su venta por Internet. Desde 
	su web podrá realizar la gestión de los clientes, la gestión de los pedidos, la gestión de las
	facturas, las formas de pago, etc.<br>
	<%= link_to plantilla4 %>
</div>
<div class="columna2" style="float: right">
	<h3>Web Personalizada: dependiendo del proyecto</h3>
	Selección de los requisitos de la web por parte del cliente. La construcción de la web se
	realiza desde cero, sin plantillas y a medida según las especificaciones que usted nos indique. <br>

	<%= link_to plantilla5 %>
</div>
</p>

app/views/pages/servicios.html.erb
<%= render 'layouts/promotion' %>
<h1>
Servicios
</h1> 
<p>
<b>Usabi</b> ofrece distintos <b>productos y servicios</b> orientados principalmente 
al desarrollo de aplicaciones <b>web</b> y aplicaciones para dispositivos móviles basados 
en iOS para <b>Iphone y Ipad</b> o la plataforma <b>Android</b>.

A continuación se muestra un listado de servicios y precios estimativos. 
Siempre realizaremos un presupuesto al cliente: 

<div class="columnapeque" style="float: right">
	<%= link_to "Aplicaciones web", aplicacionesweb_path %> <br>
	<%= link_to promocion, aplicacionesweb_path %> 

</div> 
<div class="columnapeque" style="float: left">
	<%= link_to "Aplicaciones para smartphones", appsmartphones_path %><br>
	<%= link_to iphone, appsmartphones_path %> 
</div>
<div class="columnapeque" style="float: right">
	<%= link_to "Paquetes web", paquetesweb_path %><br>
	<%= link_to modulos, paquetesweb_path %> 

</div>
<div class="columnapeque" style="float: left">
	<%= link_to "Servicios web", serviciosweb_path %><br>
	<%= link_to seo, serviciosweb_path %> 

</div>

app/views/pages/serviciosweb.html.erb
<%= render 'layouts/promotion' %>

<h1>
	Servicios web
</h1> 
<p>
Asociada a la creación de una página web tenemos distintos servicios:
<ul>
	<li>Posicionamiento web</li>
	<li>Dominio y hosting</li>
	<li>Actualización de contenidos</li>
	<li>Copias de seguridad</li>
	<li>Cursos de formación</li>
</ul>
	<%= link_to seo %> 

</p>

app/views/shared/_error_messages.html.erb
<% if @support.errors.any? %> 
	<div id="error_explanation">
		<h2><%= pluralize(@support.errors.count, "error") %> No se ha enviado el mensaje:</h2>
		<p>Hay errores en las siguientes celdas:</p> 
			<ul> <% @support.errors.full_messages.each do |msg| %>
				<li><%= msg %></li> 
				<% end %> 
			</ul>
	</div> 
<% end %>

app/views/supports/_form.html.erb
<% # app/views/supports/_form.html.erb %>

<% form_for @support, :url => { :action => "create" }, :html => { :method => :post } do |f| %>
  <p>
    <%= f.label "Nombre" %><br>
    <%= f.text_field :sender_name %> <br>
    <%= f.label "Email" %><br>
    <%= f.text_field :email %><br>
    <%= f.label "Tipo de consulta" %><br>
    <%= f.select :support_type, options_for_select(["Pregunta", "Idea"]) %><br>
    <%= f.label "Details" %><br>
    <%= f.text_area :content %><br>
    <%= f.submit "Enviar" %>
  </p>
<% end %>

app/views/supports/new.html.erb
	<%= render 'shared/error_messages'%>

<h2>Contacte con nosotros </h2>

<%= render 'form' %>

app/views/users/index.html.erb
<%= @user.name %>, <%= @user.email %>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>